name: Print GHA claim (oidc)

permissions:
  id-token: write
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  print_gha_claim:
    runs-on: ubuntu-latest
    #environment:
    # name: prod
    steps:
      - name: Print ACTIONS_ID_TOKEN_REQUEST_URL
        run: echo $ACTIONS_ID_TOKEN_REQUEST_URL
      - name: Print token payload
        run: |
          ID_TOKEN=$(curl -s \
            -H "Authorization: bearer ${ACTIONS_ID_TOKEN_REQUEST_TOKEN}" \
            -H "Accept: application/json; api-version=2.0" \
            -H "Content-Type: application/json" \
            -d "{}" "${ACTIONS_ID_TOKEN_REQUEST_URL}" \
              | jq -r '.value')
          PAYLOAD_RAW=$(echo -n "$ID_TOKEN" | cut -d '.' -f2)

          # throws error due to padding
          # echo -n "$PAYLOAD_RAW" | base64 -d

          # fixes padding error
          # ref: https://unix.stackexchange.com/questions/631501/base64-d-decodes-but-says-invalid-input
          PAYLOAD=$(echo "$PAYLOAD_RAW"==== | fold -w 4 | sed '$ d' | tr -d '\n' | base64 --decode)
          echo "$PAYLOAD" | jq

